### ISSUE TITLE
Possible off by one on counts

### ISSUE THREAD

**Issue by tmcw** [tmcw-up-for-adoption/xtw#8]
reported by @oeon on twitter

**Comment by NigelGreenway** [comment]
This is still the case.

Are there any updates on the issue?

![bug](https://f.cloud.github.com/assets/2984008/1669016/b4a25a84-5c6f-11e3-8fde-416e1d4bc5f0.jpg)

**Comment by tmcw** [comment]
Sorry, I don't actively use taskwarrior anymore - feel free to fork & fix if you can.
